// French names for all FIFA 3-letter codes likely to appear at WC 2026.
// Falls back to the API's English name (passed alongside) when the code is unknown.
export const TEAM_NAMES_FR: Record<string, string> = {
  AFG: "Afghanistan",
  ALB: "Albanie",
  ALG: "Algérie",
  AND: "Andorre",
  ANG: "Angola",
  ARG: "Argentine",
  ARM: "Arménie",
  AUS: "Australie",
  AUT: "Autriche",
  AZE: "Azerbaïdjan",
  BAH: "Bahamas",
  BAN: "Bangladesh",
  BEL: "Belgique",
  BEN: "Bénin",
  BFA: "Burkina Faso",
  BHR: "Bahreïn",
  BIH: "Bosnie-Herzégovine",
  BLR: "Biélorussie",
  BOL: "Bolivie",
  BOT: "Botswana",
  BRA: "Brésil",
  BUL: "Bulgarie",
  BUR: "Burundi",
  CAM: "Cambodge",
  CAN: "Canada",
  CHA: "Tchad",
  CHI: "Chili",
  CHN: "Chine",
  CIV: "Côte d'Ivoire",
  CMR: "Cameroun",
  COD: "RD Congo",
  COL: "Colombie",
  COM: "Comores",
  CPV: "Cap-Vert",
  CRC: "Costa Rica",
  CRO: "Croatie",
  CTA: "Centrafrique",
  CUB: "Cuba",
  CUW: "Curaçao",
  CYP: "Chypre",
  CZE: "Tchéquie",
  DEN: "Danemark",
  DOM: "Rép. Dominicaine",
  ECU: "Équateur",
  EGY: "Égypte",
  ENG: "Angleterre",
  ESP: "Espagne",
  EST: "Estonie",
  ETH: "Éthiopie",
  FIN: "Finlande",
  FRA: "France",
  FRO: "Îles Féroé",
  GAB: "Gabon",
  GAM: "Gambie",
  GEO: "Géorgie",
  GER: "Allemagne",
  GHA: "Ghana",
  GIB: "Gibraltar",
  GNB: "Guinée-Bissau",
  GRE: "Grèce",
  GUI: "Guinée",
  HAI: "Haïti",
  HKG: "Hong Kong",
  HON: "Honduras",
  HUN: "Hongrie",
  IDN: "Indonésie",
  IND: "Inde",
  IRL: "Irlande",
  IRN: "Iran",
  IRQ: "Irak",
  ISL: "Islande",
  ISR: "Israël",
  ITA: "Italie",
  JAM: "Jamaïque",
  JOR: "Jordanie",
  JPN: "Japon",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KGZ: "Kirghizistan",
  KOR: "Corée du Sud",
  KOS: "Kosovo",
  KSA: "Arabie saoudite",
  KUW: "Koweït",
  LAO: "Laos",
  LBN: "Liban",
  LBR: "Liberia",
  LBY: "Libye",
  LCA: "Sainte-Lucie",
  LES: "Lesotho",
  LIE: "Liechtenstein",
  LTU: "Lituanie",
  LUX: "Luxembourg",
  LVA: "Lettonie",
  MAD: "Madagascar",
  MAR: "Maroc",
  MAS: "Malaisie",
  MDA: "Moldavie",
  MDV: "Maldives",
  MEX: "Mexique",
  MKD: "Macédoine du Nord",
  MLI: "Mali",
  MLT: "Malte",
  MNE: "Monténégro",
  MOZ: "Mozambique",
  MRI: "Maurice",
  MTN: "Mauritanie",
  MWI: "Malawi",
  MYA: "Myanmar",
  NAM: "Namibie",
  NCA: "Nicaragua",
  NCL: "Nouvelle-Calédonie",
  NED: "Pays-Bas",
  NEP: "Népal",
  NGA: "Nigeria",
  NIG: "Niger",
  NOR: "Norvège",
  NZL: "Nouvelle-Zélande",
  OMA: "Oman",
  PAK: "Pakistan",
  PAN: "Panama",
  PAR: "Paraguay",
  PER: "Pérou",
  PHI: "Philippines",
  PLE: "Palestine",
  POL: "Pologne",
  POR: "Portugal",
  PRK: "Corée du Nord",
  PUR: "Porto Rico",
  QAT: "Qatar",
  ROU: "Roumanie",
  RSA: "Afrique du Sud",
  RUS: "Russie",
  RWA: "Rwanda",
  SCO: "Écosse",
  SEN: "Sénégal",
  SIN: "Singapour",
  SLE: "Sierra Leone",
  SLV: "Salvador",
  SMR: "Saint-Marin",
  SOM: "Somalie",
  SRB: "Serbie",
  SRI: "Sri Lanka",
  SSD: "Soudan du Sud",
  STP: "Sao Tomé-et-Principe",
  SUD: "Soudan",
  SUI: "Suisse",
  SUR: "Suriname",
  SVK: "Slovaquie",
  SVN: "Slovénie",
  SWE: "Suède",
  SWZ: "Eswatini",
  SYR: "Syrie",
  TAH: "Tahiti",
  TAN: "Tanzanie",
  THA: "Thaïlande",
  TJK: "Tadjikistan",
  TKM: "Turkménistan",
  TLS: "Timor oriental",
  TOG: "Togo",
  TPE: "Taïwan",
  TRI: "Trinité-et-Tobago",
  TUN: "Tunisie",
  TUR: "Turquie",
  UAE: "Émirats arabes unis",
  UGA: "Ouganda",
  UKR: "Ukraine",
  URU: "Uruguay",
  USA: "États-Unis",
  UZB: "Ouzbékistan",
  VAN: "Vanuatu",
  VEN: "Venezuela",
  VIE: "Viêt Nam",
  WAL: "Pays de Galles",
  YEM: "Yémen",
  ZAM: "Zambie",
  ZIM: "Zimbabwe",
};

export function teamNameFr(code: string, fallback?: string): string {
  return TEAM_NAMES_FR[code?.toUpperCase()] ?? fallback ?? code;
}

export function teamAbbr(code: string): string {
  return (code ?? "").toUpperCase().slice(0, 3);
}

// FIFA 3-letter code → ISO 3166-1 alpha-2 (lowercase) for flag CDN lookups.
// Covers every entry in TEAM_NAMES_FR; falls back to lowercase code otherwise.
const FIFA_TO_ISO2: Record<string, string> = {
  AFG: "af", ALB: "al", ALG: "dz", AND: "ad", ANG: "ao", ARG: "ar", ARM: "am",
  AUS: "au", AUT: "at", AZE: "az", BAH: "bs", BAN: "bd", BEL: "be", BEN: "bj",
  BFA: "bf", BHR: "bh", BIH: "ba", BLR: "by", BOL: "bo", BOT: "bw", BRA: "br",
  BUL: "bg", BUR: "bi", CAM: "kh", CAN: "ca", CHA: "td", CHI: "cl", CHN: "cn",
  CIV: "ci", CMR: "cm", COD: "cd", COL: "co", COM: "km", CPV: "cv", CRC: "cr",
  CRO: "hr", CTA: "cf", CUB: "cu", CUW: "cw", CYP: "cy", CZE: "cz", DEN: "dk",
  DOM: "do", ECU: "ec", EGY: "eg", ENG: "gb-eng", EQG: "gq", ESP: "es",
  EST: "ee", ETH: "et", FIN: "fi", FRA: "fr", FRO: "fo", GAB: "ga", GAM: "gm",
  GEO: "ge", GER: "de", GHA: "gh", GIB: "gi", GNB: "gw", GRE: "gr", GUI: "gn",
  HAI: "ht", HKG: "hk", HON: "hn", HUN: "hu", IDN: "id", IND: "in", IRL: "ie",
  IRN: "ir", IRQ: "iq", ISL: "is", ISR: "il", ITA: "it", JAM: "jm", JOR: "jo",
  JPN: "jp", KAZ: "kz", KEN: "ke", KGZ: "kg", KOR: "kr", KOS: "xk", KSA: "sa",
  KUW: "kw", LAO: "la", LBN: "lb", LBR: "lr", LBY: "ly", LCA: "lc", LES: "ls",
  LIE: "li", LTU: "lt", LUX: "lu", LVA: "lv", MAD: "mg", MAR: "ma", MAS: "my",
  MDA: "md", MDV: "mv", MEX: "mx", MKD: "mk", MLI: "ml", MLT: "mt", MNE: "me",
  MOZ: "mz", MRI: "mu", MTN: "mr", MWI: "mw", MYA: "mm", NAM: "na", NCA: "ni",
  NCL: "nc", NED: "nl", NEP: "np", NGA: "ng", NIG: "ne", NOR: "no", NZL: "nz",
  OMA: "om", PAK: "pk", PAN: "pa", PAR: "py", PER: "pe", PHI: "ph", PLE: "ps",
  POL: "pl", POR: "pt", PRK: "kp", PUR: "pr", QAT: "qa", ROU: "ro", RSA: "za",
  RUS: "ru", RWA: "rw", SCO: "gb-sct", SEN: "sn", SIN: "sg", SLE: "sl",
  SLV: "sv", SMR: "sm", SOM: "so", SRB: "rs", SRI: "lk", SSD: "ss", STP: "st",
  SUD: "sd", SUI: "ch", SUR: "sr", SVK: "sk", SVN: "si", SWE: "se", SWZ: "sz",
  SYR: "sy", TAH: "pf", TAN: "tz", THA: "th", TJK: "tj", TKM: "tm", TLS: "tl",
  TOG: "tg", TPE: "tw", TRI: "tt", TUN: "tn", TUR: "tr", UAE: "ae", UGA: "ug",
  UKR: "ua", URU: "uy", USA: "us", UZB: "uz", VAN: "vu", VEN: "ve", VIE: "vn",
  WAL: "gb-wls", YEM: "ye", ZAM: "zm", ZIM: "zw",
};

function fifaToIso2(code: string): string | null {
  const c = (code ?? "").toUpperCase();
  if (!c) return null;
  return FIFA_TO_ISO2[c] ?? c.toLowerCase();
}

export function flagUrl(code: string, override?: string): string | undefined {
  if (override) return override;
  const iso = fifaToIso2(code);
  return iso ? `https://media.api-sports.io/flags/${iso}.svg` : undefined;
}

// English country name (as returned by BSD `home_team` / `country` fields)
// → FIFA 3-letter code.
const COUNTRY_TO_FIFA: Record<string, string> = {
  "afghanistan": "AFG", "albania": "ALB", "algeria": "ALG", "andorra": "AND",
  "angola": "ANG", "argentina": "ARG", "armenia": "ARM", "australia": "AUS",
  "austria": "AUT", "azerbaijan": "AZE", "bahamas": "BAH", "bahrain": "BHR",
  "bangladesh": "BAN", "belarus": "BLR", "belgium": "BEL", "benin": "BEN",
  "bolivia": "BOL", "bosnia": "BIH", "bosnia and herzegovina": "BIH",
  "botswana": "BOT", "brazil": "BRA", "bulgaria": "BUL", "burkina faso": "BFA",
  "burundi": "BUR", "cambodia": "CAM", "cameroon": "CMR", "canada": "CAN",
  "cape verde": "CPV", "central african republic": "CTA", "chad": "CHA",
  "chile": "CHI", "china": "CHN", "colombia": "COL", "comoros": "COM",
  "congo": "COD", "costa rica": "CRC", "croatia": "CRO", "cuba": "CUB",
  "curacao": "CUW", "cyprus": "CYP", "czech republic": "CZE", "czechia": "CZE",
  "denmark": "DEN", "dominican republic": "DOM", "dr congo": "COD",
  "ecuador": "ECU", "egypt": "EGY", "el salvador": "SLV", "england": "ENG",
  "equatorial guinea": "EQG", "estonia": "EST", "ethiopia": "ETH",
  "faroe islands": "FRO", "finland": "FIN", "france": "FRA", "gabon": "GAB",
  "gambia": "GAM", "georgia": "GEO", "germany": "GER", "ghana": "GHA",
  "gibraltar": "GIB", "greece": "GRE", "guinea": "GUI", "guinea-bissau": "GNB",
  "haiti": "HAI", "honduras": "HON", "hong kong": "HKG", "hungary": "HUN",
  "iceland": "ISL", "india": "IND", "indonesia": "IDN", "iran": "IRN",
  "iraq": "IRQ", "ireland": "IRL", "israel": "ISR", "italy": "ITA",
  "ivory coast": "CIV", "jamaica": "JAM", "japan": "JPN", "jordan": "JOR",
  "kazakhstan": "KAZ", "kenya": "KEN", "kosovo": "KOS", "kuwait": "KUW",
  "kyrgyzstan": "KGZ", "laos": "LAO", "latvia": "LVA", "lebanon": "LBN",
  "lesotho": "LES", "liberia": "LBR", "libya": "LBY", "liechtenstein": "LIE",
  "lithuania": "LTU", "luxembourg": "LUX", "madagascar": "MAD", "malawi": "MWI",
  "malaysia": "MAS", "maldives": "MDV", "mali": "MLI", "malta": "MLT",
  "mauritania": "MTN", "mauritius": "MRI", "mexico": "MEX", "moldova": "MDA",
  "montenegro": "MNE", "morocco": "MAR", "mozambique": "MOZ", "myanmar": "MYA",
  "namibia": "NAM", "nepal": "NEP", "netherlands": "NED", "new caledonia": "NCL",
  "new zealand": "NZL", "nicaragua": "NCA", "niger": "NIG", "nigeria": "NGA",
  "north korea": "PRK", "north macedonia": "MKD", "norway": "NOR", "oman": "OMA",
  "pakistan": "PAK", "palestine": "PLE", "panama": "PAN", "paraguay": "PAR",
  "peru": "PER", "philippines": "PHI", "poland": "POL", "portugal": "POR",
  "puerto rico": "PUR", "qatar": "QAT", "republic of ireland": "IRL",
  "romania": "ROU", "russia": "RUS", "rwanda": "RWA", "san marino": "SMR",
  "saudi arabia": "KSA", "scotland": "SCO", "senegal": "SEN", "serbia": "SRB",
  "sierra leone": "SLE", "singapore": "SIN", "slovakia": "SVK", "slovenia": "SVN",
  "somalia": "SOM", "south africa": "RSA", "south korea": "KOR",
  "south sudan": "SSD", "spain": "ESP", "sri lanka": "SRI", "sudan": "SUD",
  "suriname": "SUR", "swaziland": "SWZ", "eswatini": "SWZ", "sweden": "SWE",
  "switzerland": "SUI", "syria": "SYR", "tahiti": "TAH", "taiwan": "TPE",
  "tajikistan": "TJK", "tanzania": "TAN", "thailand": "THA", "timor-leste": "TLS",
  "togo": "TOG", "trinidad and tobago": "TRI", "tunisia": "TUN", "turkey": "TUR",
  "turkmenistan": "TKM", "uganda": "UGA", "ukraine": "UKR",
  "united arab emirates": "UAE", "united states": "USA", "usa": "USA",
  "uruguay": "URU", "uzbekistan": "UZB", "vanuatu": "VAN", "venezuela": "VEN",
  "vietnam": "VIE", "wales": "WAL", "yemen": "YEM", "zambia": "ZAM",
  "zimbabwe": "ZIM",
};

function normalize(s: string): string {
  return s
    .normalize("NFD")
    .replace(/\p{M}/gu, "") // strip combining marks (any Unicode mark)
    .toLowerCase()
    .replace(/['’`]/g, "") // apostrophes (straight + curly)
    .replace(/&/g, " and ")
    .replace(/[-_.]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const COUNTRY_TO_FIFA_NORMALIZED: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(COUNTRY_TO_FIFA)) out[normalize(k)] = v;
  // Variants commonly returned by sports APIs
  const aliases: Record<string, string> = {
    "cote divoire": "CIV",
    "ivory coast": "CIV",
    "republic of ireland": "IRL",
    "korea republic": "KOR",
    "korea south": "KOR",
    "korea dpr": "PRK",
    "korea north": "PRK",
    "iran islamic republic of": "IRN",
    "czech republic": "CZE",
    "czechia": "CZE",
    "bosnia and herzegovina": "BIH",
    "bosnia": "BIH",
    "dr congo": "COD",
    "congo dr": "COD",
    "democratic republic of the congo": "COD",
    "congo democratic republic": "COD",
    "cape verde": "CPV",
    "cabo verde": "CPV",
    "saudi arabia": "KSA",
    "south africa": "RSA",
    "south korea": "KOR",
    "north korea": "PRK",
    "new zealand": "NZL",
    "united states": "USA",
    "united states of america": "USA",
    "united arab emirates": "UAE",
    "trinidad and tobago": "TRI",
    "north macedonia": "MKD",
    "macedonia": "MKD",
    "curacao": "CUW",
    "turkiye": "TUR",
    "bosnia herzegovina": "BIH",
    "england": "ENG",
    "scotland": "SCO",
    "wales": "WAL",
    "northern ireland": "NIR",
  };
  for (const [k, v] of Object.entries(aliases)) out[normalize(k)] = v;
  return out;
})();

export function countryToFifa(name: string | null | undefined): string {
  if (!name) return "";
  const key = normalize(name);
  return COUNTRY_TO_FIFA_NORMALIZED[key] ?? "";
}
